### PR TITLE
Add maximum module speed

### PR DESCRIPTION
**Pull request by hhilal123**
Creates a new constructor that allows passing of maximum module speed. The class now contains the default value for maximum speed and move() passes the instance variable for maximum module speed when calling normalizeModuleVectors().

### CODE REVIEW

**Review by Mineinjava — APPROVED** [review]
LGTM

**Review by Astr0clad — APPROVED** [review]
LGTM

**Comment by Mineinjava** [comment]
Has not been tested

**Comment by Mineinjava** [comment]
Drivebase doesn't work as of now, will test when it works hopefully sometime this week

**Comment by Mineinjava** [comment]
@hhilal123 you are 140+ commits behind if you could rebase that would be great.

**Comment by Mineinjava** [comment]
Superseded by #38 
fixes conflicts

**Pull request closed without merging**
