### PR TITLE
Fix rotation scaling with point distance

### PR DESCRIPTION
**Pull request by 2141Robotics**
still needs to adjust for speed

### CODE REVIEW

**Comment by Mineinjava** [comment]
@Astr0clad do you think the rotation speed should scale with translational speed?

**Review by Astr0clad — APPROVED** [review]
W naming

**Comment by 2141Robotics** [comment]
@Astr0clad pls re review

- mkauffman

**Comment by Mineinjava** [comment]
Confirmed working

**Review by Astr0clad — COMMENTED** [review]
lgtm

**Pull request merged**
