### PR TITLE
refactored-marcus-is-dumb

### LINKED ISSUE #32: Refactor ...pathing/Path.java vector_last_to_current_point() to use camel case

### PR DESCRIPTION
**Pull request by hhilal123**
fixes #32

### CODE REVIEW

**Review by Mineinjava — APPROVED** [review]
Lgtm

**Comment by Mineinjava** [comment]
@Astr0clad review

**Review by Astr0clad — APPROVED** [review]
lgtm, thanks for using best practice

**Comment by Mineinjava** [comment]
"best practice" is saying that Marcus is dumb :p

**Pull request merged**
